name: CI

on: [push]

jobs:
  sast_scan: 
    name: Run SAST Scan with Bandit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Pyhton
      uses: actions/checkout@v2
      with:
        python-version: 3.9

    - name: Install Bandit
      run: pip install bandit

    - name: Run bandit scan
      run: bandit -r .
